# Generated by Django 3.2.9 on 2022-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquizenglish', '0002_question_giaidap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='giaidap',
            field=models.TextField(),
        ),
    ]
